# -*- coding: utf-8 -*-
"""
Tests for POST /simprint.

The fixture corpus in `tests/data/simprint_fixtures.json` is generated by running iscc-search's
reference implementation (`iscc_search.processing.text_simprints`) via
`develop/gen_simprint_fixtures.py`. The endpoint promises byte-identical output.
"""

import json
import pathlib
import pytest
from httpx import codes


FIXTURES = json.loads((pathlib.Path(__file__).parent / "data" / "simprint_fixtures.json").read_text(encoding="utf-8"))


@pytest.mark.parametrize("name", sorted(FIXTURES))
def test_simprint_identical_to_iscc_search_reference(api, name):
    fixture = FIXTURES[name]
    response = api.post("/simprint", json={"text": fixture["text"]})
    assert response.status_code == codes.OK
    assert response.json() == fixture["expected"]


def test_simprint_empty_text(api):
    response = api.post("/simprint", json={"text": ""})
    assert response.status_code == codes.BAD_REQUEST


def test_simprint_missing_text(api):
    response = api.post("/simprint", json={})
    assert response.status_code == codes.BAD_REQUEST


def test_simprint_invalid_json(api):
    response = api.post("/simprint", content=b"not json", headers={"Content-Type": "application/json"})
    assert response.status_code == codes.BAD_REQUEST


def test_simprint_oversize_text(api):
    # Test servers run with ISCC_WEB_MAX_UPLOAD_SIZE=1000000 (tests/conftest.py).
    response = api.post("/simprint", json={"text": "a" * 1_000_001})
    assert response.status_code == codes.BAD_REQUEST
