name: Test Backend
on: [push, pull_request]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.2.1

      - name: Install Dependencies
        run: poetry install

      - name: Run Tests (Pure Python with coverage)
        run: poetry run pytest
