name: Test Backend

on:
  push:
    branches:
  pull_request:

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: uv sync

      - name: Run Tests
        run: uv run pytest
