name: Test Docker image build
on:
  pull_request:
jobs:
  push_to_registry:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: |
            ghcr.io/iscc/iscc-web:${{ github.sha }}
          cache-from: type=gha,scope=app
          cache-to: type=gha,scope=app,mode=max
      - name: Fetch index
        run: |
          # start container
          docker run --name=iscc-web -d -p 8000:8000 ghcr.io/iscc/iscc-web:${{ github.sha }}

          cleanup() {
            docker logs iscc-web
            docker kill iscc-web
          }
          trap cleanup EXIT INT TERM

          # check if the service returns HTTP 200
          wget --retry-connrefused --waitretry=1 --read-timeout=1 --timeout=1 -t 10 http://localhost:8000

          if [ $? = 0 ]; then
            echo "Fetching index successful"
          else
            echo "Fetching index failed!"
            exit 1
          fi

