name: Test Docker image build
on:
  pull_request:
jobs:
  push_to_registry:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: |
            ghcr.io/iscc/iscc-service-generator:${{ github.sha }}
          cache-from: type=gha,scope=app
          cache-to: type=gha,scope=app,mode=max
      - name: Fetch index
        run: |
          # start container
          container_id=$(docker run --rm -d -p 8000:8000 ghcr.io/iscc/iscc-web:${{ github.sha }})

          # check if the service returns HTTP 200
          curl -o /dev/null -w "%{http_code}" \
            --connect-timeout 5 \
            --max-time 10 \
            --retry 5 \
            --retry-delay 5 \
            --retry-max-time 40 \
            --retry-all-errors http://localhost:8000 | grep '^200$'

          docker kill $container_id
